name       : lightzone
version    : 4.1.2
release    : 1
source     :
    - https://github.com/ktgw0316/LightZone/archive/4.1.2.tar.gz : 46d9a849e500eaa403fd7c8f03220828a9283ec96a45b2d51aa2adff5da5ecce
license    : BSD-3-Clause
summary    : LightZone - digital darkroom and photo editor
description: |
    LightZone is a professional-level digital darkroom and photo editor. It includes RAW processing and editing. Rather than using layers in the way that other photo editors do, LightZone lets the user build up a stack of tools which can be rearranged, readjusted, turned off and on, and removed from the stack. It's a completely non-destructive editor, where any of the tools can be re-adjusted or modified later — even in a different editing session. A tool stack can even be copied to a batch of photos at one time. LightZone always operates in a 16-bit linear color space with the wide gamut of ProPhoto RGB.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
